### Creating arrays from lists tuples and using built - in Numpy functions

##### List


In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr.ndim

1

In [5]:
arr.shape

(9,)

In [6]:
arr.size

9

##### Tuple

In [7]:
arr1=np.array((1,2,3,4,5,6,7,8,9))
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr1.ndim

1

In [9]:
arr1.shape

(9,)

In [10]:
arr1.size

9

### Creating 1d array using a list of numbers from 1 to 10

In [12]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Create a 2D array (3×3) using a nested list.


In [15]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr1.shape

(3, 3)

In [17]:
arr1.ndim

2

In [20]:
arr1.size

9

Create a NumPy array from a tuple of 5 elements.


In [22]:
arr2=np.array((1,2,3,4,5))
arr2

array([1, 2, 3, 4, 5])

### B. Using Built-in Creation Functions

##### Create an array of zeros with shape (4,4).

In [25]:
arr1=np.zeros((4,4),dtype= "int")
arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [27]:
arr1.shape

(4, 4)

##### Create an array of ones with shape (2,5).


In [26]:
arr2=np.ones((2,5),dtype="int")
arr2

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [28]:
arr2.shape

(2, 5)

##### Create an array filled with the number 7 of shape (3,3).


In [29]:
arr3=np.full((3,3),7)
arr3

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [30]:
arr3.shape

(3, 3)

### C. Range-Based Arrays

##### Create an array of numbers from 0 to 20 with a step of 2.

In [32]:
arr=np.arange(0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

##### Create an array of 10 evenly spaced numbers between 1 and 5.

In [34]:
arr1=np.linspace(1,5,10)
arr1

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

### D. Identity & Diagonal

##### Create a 4×4 identity matrix.


In [38]:
arr=np.identity((4),dtype="int")
arr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

Extract the diagonal elements from a 3×3 array.


In [47]:
arr1=np.arange(1,10).reshape(3,3)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
result=np.diag(arr1)
print(result)

[1 5 9]


Create a diagonal matrix using the values [1, 2, 3, 4].

In [48]:
values=[1,2,3,4]
arr2=np.diag(values)
arr2

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### E. Dimensions & Shape


Create a 2D array and print:
- its shape
- number of dimensions
- total number of elements


In [52]:
arr=np.arange(1,7).reshape(2,3)
print(arr)
print(arr.shape)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


#### Create a 3×3 array of your choice and print the diagonal elements.


In [55]:
arr1=np.arange(9).reshape(3,3)

In [56]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:
result=np.diag(arr1)
result

array([0, 4, 8])

### F. Mixed Practice

Create a 5×5 matrix with zeros but set the diagonal elements to 1.

In [64]:
arr=np.eye((5),dtype="int")
arr

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Create three arrays using zeros(), ones(), and arange(), then print their shapes and compare.

In [68]:
arr1=np.zeros((3,3),dtype="int")
arr1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [70]:
arr2=np.ones((3,3),dtype="int")
arr2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [71]:
arr3=np.arange(9).reshape(3,3)
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(3, 3)
(3, 3)
(3, 3)
