Create a single-element NumPy array containing the value 7.




In [3]:
import numpy as np

In [5]:
arr=np.array([7])
print(arr)

[7]


Create a one-dimensional array containing the numbers 10, 20, 30, 40, and 50.

In [6]:
arr=np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


Create a two-dimensional array forming a 3 × 3 matrix with numbers from 1 to 9.

In [7]:
arr=np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Create a three-dimensional array with shape (2, 2, 3) containing numbers from 1 to 12.

In [8]:
arr=np.arange(12).reshape(2,2,3)
print(arr)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


How do you check the number of dimensions?


In [9]:
arr=np.arange(12).reshape(2,2,3)
print(arr.ndim)

3


In [10]:
type(arr)

numpy.ndarray

## Array Creation Methods

Create a 3 × 3 identity matrix (all diagonal elements are 1 and the rest are 0).

In [14]:
arr=np.identity(3,dtype="int")
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


Create a 2 × 3 matrix filled entirely with zeros.

In [17]:
arr=np.zeros((2,3),dtype="int")
print(arr)

[[0 0 0]
 [0 0 0]]


Create a 2 × 3 matrix filled entirely with ones.

In [19]:
arr=np.ones((2,3),dtype="int")
print(arr)

[[1 1 1]
 [1 1 1]]


Create a 2 × 3 matrix with uninitialized values (empty array).

In [21]:
arr=np.empty((2,3))
print(arr)

[[5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]]


Create a 3 × 3 matrix where every element has the value 9.


In [22]:
arr=np.full((3,3),9,dtype="int")
print(arr)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


Transform a one-dimensional array of 8 elements into a three-dimensional array with shape (2, 2, 2).

In [26]:
arr=np.arange(1,9)
print(arr)

[1 2 3 4 5 6 7 8]


In [27]:
reshape=arr.reshape(2,2,2)
print(reshape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Linspace & Arrange Concepts


Create a one-dimensional array of 5 evenly spaced numbers between 0 and 10, including both endpoints.

In [29]:
arr=np.linspace(0,10,5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

Create a sequence starting at 0 and ending before 1, with a step size of 0.1. Explain any floating-point precision issues you observe.

In [31]:
arr = np.arange(0, 1, 0.1)

print(arr)


[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


Create an array of integers starting from 5 up to 20, increasing by 3 each time.

In [33]:
arr=np.arange(5,20,3)
print(arr)

[ 5  8 11 14 17]


Create 6 evenly spaced numbers between 5 and 10, excluding the endpoint value (10)

In [38]:
arr=np.linspace(5,10,6,dtype="int")
arr

array([ 5,  6,  7,  8,  9, 10])

Use np.info() on a 2D array and explore what information it provides

In [41]:
arr=np.arange(1,9).reshape(2,4)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [43]:
np.info(arr)

class:  ndarray
shape:  (2, 4)
strides:  (32, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x1dfa6bb2590
byteorder:  little
byteswap:  False
type: int64


## Random Number Generation


Create an array of 5 random integers between 0 and 9.

In [48]:
arr=np.random.randint(0,9,size=5)
print(arr)

[2 0 3 2 3]


Create a 2 × 3 array of random integers between 50 and 100.

In [49]:
arr=np.random.randint(50,100,size=(2,3))
print(arr)

[[63 72 76]
 [70 94 54]]


Given the array of test scores [2, 8, 12, 18, 25], modify the array so that all values less than 5 become 5 and all values greater than 15 become 15.

In [50]:
test_scores=[2,8,12,18,25]

In [52]:
arr=[]
for i in test_scores:
    if i<5:
        arr.append(5)
    elif i>15:
        arr.append(15)
    else:
        arr.append(i)

In [53]:
arr

[5, 8, 12, 15, 15]

Given the exam scores [10, 20, 20, 30, 40, 50], calculate the mean, median, variance, and standard deviation. 

In [54]:
scores= [10, 20, 20, 30, 40, 50]
mean=np.mean(scores)
median=np.median(scores)
variance=np.var(scores)
std=np.std(scores)
print(mean)
print(median)
print(variance)
print(std)

28.333333333333332
25.0
180.55555555555557
13.43709624716425


## Array Attributes: Shape, Size, and Memory

Find the shape, total number of elements, and number of dimensions of an array.

- A.Which attributes do you use?
- B.Write example code.


In [55]:
arr=np.array([[2,3,4],[5,6,7],[8,9,0]])
arr

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 0]])

In [56]:
print(arr.shape)

(3, 3)


In [59]:
print(arr.size)

9


In [60]:
print(len(arr))

3


In [61]:
print(arr.ndim)

2


For the array [[1, 2, 3], [4, 5, 6]], determine its shape.

In [67]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr\
     )

[[1 2 3]
 [4 5 6]]


In [69]:
arr.size

6

Determine how many bytes each element of an array uses.
  A.Which attribute gives this information?

In [71]:
arr=np.array([1,2,3])
print(arr.nbytes)

24


In [72]:
23/3

7.666666666666667

Explain how the total memory used by an array relates to the element size and the number of elements.

In [75]:
arr = np.array([1, 2, 3], dtype=np.int32)

print("Item size:", arr.itemsize)

Item size: 4


For an array of three 32-bit integers, calculate the total memory used in bytes.

In [76]:
arr=np.array([1,2,3,4],dtype=np.int32)
print(arr.itemsize)
print(arr.nbytes)
print(arr.size)

4
16
4


For a 3 × 3 array of 64-bit floating-point numbers, calculate its total memory usage in bytes.

In [79]:
arr=np.arange(9,dtype=np.float64).reshape(3,3)
print(arr)


[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [81]:
print("total memeory",arr.nbytes)

total memeory 72


## Python List vs NumPy Array

Explain the differences between Python lists and NumPy arrays in terms of memory usage, operations, and performance.

- ## Python Lists
- Store references (pointers) to objects, not the raw data itself.
- Each element can be of a different type, so extra memory is needed for type information and object overhead.
- Memory layout is scattered and less efficient.
- ## NumPy Arrays
- Store elements in a contiguous block of memory.
- All elements must be of the same data type (homogeneous).
- Much more compact: only the raw data plus minimal metadata is


Multiply a Python list and a NumPy array by 2. Compare the results.

In [83]:
py_list = [1, 2, 3]
result_list = py_list * 2
print(result_list)


[1, 2, 3, 1, 2, 3]


In [84]:
np_array = np.array([1, 2, 3])
result_array = np_array * 2
print(result_array)


[2 4 6]


Add two Python lists and then add two NumPy arrays containing the same values. Compare the results.

In [85]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]

result_list = list1 + list2
print(result_list)


[1, 2, 3, 4, 5, 6]


In [86]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result_array = arr1 + arr2
print(result_array)


[5 7 9]


Convert the Python list [10, 20, 30, 40] into a NumPy array and multiply each element by 2.

In [87]:
lst=[10,20,30,40]
import numpy as np
arr=np.array(lst)*2
arr

array([20, 40, 60, 80])

Explain why NumPy arrays are stored in contiguous memory blocks and why this is important.

- Efficient Access
- Since elements are stored back-to-back, NumPy can calculate the memory address of any element directly using simple arithmetic (base address + offset).
- This avoids the overhead of following pointers (like in Python lists).
- Vectorized Operations
- Contiguous memory allows NumPy to apply operations across entire arrays at once using optimized C loops.
- For example, multiplying an array by 2 doesn’t loop through Python objects — it applies the operation directly on raw memory.
- Cache Friendliness
- Modern CPUs use caches to speed up memory access.
- Contiguous data means sequential elements are likely to be in the same cache line, reducing cache misses and improving performance.
- Interoperability with Low-Level Libraries
- Scientific libraries (like BLAS, LAPACK) expect data in contiguous blocks.
- NumPy arrays can be passed directly to these libraries without copying or reformatting.
- Reduced Memory Overhead
- Unlike Python lists, which store references to objects, NumPy arrays store raw values.
- This compact representation saves memory, especially for large datasets.


## Indexing & Slicing

From the 1D array [10, 20, 30, 40, 50], extract the 2nd and 4th elements.

In [89]:
arr=np.array( [10, 20, 30, 40, 50])
arr[[2,4]]

array([30, 50])

From a 2D array , access the element in the first row and second column.
	a = np.array([[1,2,3],
                                  [4,5,6]])

In [90]:
 a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
a[:,1]

array([2, 5])

Explain the difference between selecting elements using an index and selecting elements using a condition (boolean indexing).

In [92]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[2])      
print(arr[1:4]) 

30
[20 30 40]


From the array [3, 7, 2, 9, 5, 10], select only the elements greater than 5.

In [94]:
arr= np.array([3, 7, 2, 9, 5, 10])
arr[arr>5]

array([ 7,  9, 10])

From the array [10, 20, 30, 40, 50, 60], select every alternate element starting from the first.

In [95]:
arr=np.array( [10, 20, 30, 40, 50, 60])
arr[::2]

array([10, 30, 50])

Replace all negative numbers in [1, -2, 3, -4, 5] with zero.

In [97]:
arr=np.array( [1, -2, 3, -4, 5] )
arr[arr<0]=0

In [98]:
arr

array([1, 0, 3, 0, 5])

Does slicing create a view or a copy in NumPy?
 -  A.Explain clearly.

In [99]:
arr=np.array([1,2,3])
arr[0:2]

array([1, 2])

In [100]:
arr.copy()

array([1, 2, 3])

## Data Types and Numeric Precision


Explain the differences between 8-bit, 16-bit, and 32-bit integers.

- 8-bit: Compact, small range, good for things like pixel values.
- 16-bit: Moderate range, often used in audio samples or medium-sized data.
- 32-bit: Large range, standard for most general-purpose computing.

Explain the differences between 16-bit and 64-bit floating-point numbers.